adi_upate_boot.sh: add options to mkdir and wget commands
analogdevicesinc/linux_image_ADI-scripts pull request #60
Opened 2023-04-25 10:36 UTC by AAndrisa

2023-04-25 10:48 UTC, nunojsa reviewed
couple of nits...

2023-04-25 10:48 UTC, nunojsa commented on adi_update_boot.sh
> +      echo -e "\nRestoring extlinux/extlinux.conf (specific to arria10 projects starting with 2021_r1 release)..."
this looks an unrelated change...

2023-04-25 10:48 UTC, nunojsa commented on adi_update_boot.sh
> +wget --no-check-certificate -nc $rpi_boot_url
the commit message should state why we need this option

2023-04-26 10:35 UTC, SRaus requested changes

2023-04-26 10:35 UTC, SRaus commented on adi_update_boot.sh
> -      echo -e "\nRestoring extlinux/extlinux.conf (specific to cyclone5 projects starting with 2021_r1 release)..."
Actually this is specific to cyclone5, but also to A10SOC starting with Quartus 20.1 Pro version.

2023-04-26 10:35 UTC, SRaus commented on adi_update_boot.sh
> +      echo -e "\nRestoring extlinux/extlinux.conf (specific to arria10 projects starting with 2021_r1 release)..."
As Nuno said, I would add another commit for updating these echo's and also would be great to optimize it a bit: 
- lines 455-465 and 479-489 are doing the same thing: restoring extlinux.conf.
- also lines 442-451 and 466-477 are restoring u-boot (src for c5soc / img for a10soc).
You can create methods and just call them here.

2023-04-27 06:29 UTC, SRaus commented on adi_update_boot.sh
> +  echo -e "\nRestoring extlinux/extlinux.conf (specific to cyclone5 projects starting with 2021_r1 release)..."
extlinux.conf file is also specific to Aria10 soc projects, not just cyclone5.

2023-04-27 06:31 UTC, SRaus requested changes
There is a typo in commit title, on file name, and one in first line of description.

2023-04-27 07:43 UTC, SRaus reviewed
There is a typo in commit title on file name.
Also, you can remove the comment change from lines 479-480 since it is handled in the other commit.

2023-04-27 10:52 UTC, SRaus approved these changes

2023-04-27 10:55 UTC, ccraluca approved these changes

2023-04-28 10:40 UTC, merged